### ISSUE TITLE
Error in semantic-release/github: Cookies must be enabled to use GitHub

### ISSUE THREAD

**Issue by koljakutschera** [codfish/semantic-release-action#99]
## Current behavior

Action always errors with:

Failed step "publish" of plugin "@semantic-release/github"
✖  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.

## Expected behavior

GitHub publish should work

## Notes

Seems to be related to: https://github.com/semantic-release/github/issues/271

## Environment

- **semantic-release** version: master (1.3.1)
- CI environment: GitHub actions
- Plugins used: /
- **semantic-release** configuration: 
```name: Versioning
on:
  push:
    branches: [master]
jobs:
  version-bumb-and-tag:
    name: Version bumb and tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}```

- CI logs:

```[10:49:42 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/npm"
[10:49:42 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
[10:49:42 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/github"
[10:49:42 AM] [semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.
    at /action/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,```

**Comment by koljakutschera** [comment]
Fixed with latest version
